Updating scripts

diff --git a/tag-education-pull-notes-from-server b/tag-education-pull-notes-from-server
--- a/tag-education-pull-notes-from-server
+++ b/tag-education-pull-notes-from-server
@@ -1,5 +1,26 @@
 #!/bin/bash
 
-# so, the notes are currently living on the server. we'd need to connect to the ssh server and then scp the notes back to us
-# on the server they live at
+# first we need to connect to it and run the save command
+
+echo "Enter ssh password:"
+read -s password
+
+SSHLOCATION="joshu@107.179.134.247"
+
+sshpass -p "$password" ssh $SSHLOCATION << EOF
+
+wsl bash -c "tag-education-server-save-files; exit"
+
+EOF
+connectionResponse=$?
+
+if [ $connectionResponse -ne 0 ]; then
+	echo "Failed to connect to ssh"
+	exit 1
+fi
+
+sshpass -p "$password" scp -r $SSHLOCATION:C:/wsl-server-file-backup/server/school/* $HOME/documents/
+
+
+
 
